---
kind: pipeline
name: Backend Test

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: composer:latest
  commands:
  - composer install --no-interaction --ignore-platform-reqs --no-plugins --no-scripts

- name: PHPUnit Test
  image: ainlavong/cp-test:latest
  commands:
  - cp .env.test .env
  - php artisan key:generate
  - vendor/bin/phpunit --configuration phpunit.xml

services:
- name: database
  image: mysql
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test
---
kind: pipeline
name: Frontend Test

platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: node:carbon-alpine
  commands:
    - npm i

- name: Test
  image: node:carbon-alpine
  commands:
    - npm test
# - name: Slack
#   image: plugins/slack
#   when:
#   status: [ success, failure ]
#   settings:
#     webhook:
#       from_secret: slack_webhook
#     channel: classrooms-drone
#     template: >
#       {{#success build.status}}
#         Build {{build.number}} succeeded. Good job.
#       {{else}}
#         Build {{build.number}} failed. Fix me please.
#       {{/success}}

# trigger:
#   event:
#   - pull_request
...
