---
kind: pipeline
name: build-test

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: composer
  commands:
  - composer install --prefer-dist

- name: PHPUnit Test
  image: php:7.3-rc-cli-alpine
  commands:
  - cp .env.test .env
  - php artisan key:generate
  - vendor/bin/phpunit --configuration phpunit.xml


# - name: slack
#   image: plugins/slack
#   when:
#     status: [ failure ]
#   settings:
#     webhook:
#       from_secret: slack_webhook
#     channel: classrooms-drone
#     template: >
#       {{#success build.status}}
#         Build {{build.number}} succeeded. Good job.
#       {{else}}
#         Build {{build.number}} failed. Fix me please.
#       {{/success}}

# trigger:
#   event:
#   - pull_request
---
kind: pipeline
name: deploy
steps:

- name: grab .env
  image: mesosphere/aws-cli
  environment:
     AWS_ACCESS_KEY_ID:
       from_secret: aws_access_key_id
     AWS_SECRET_ACCESS_KEY:
       from_secret: aws_secret_access_key
     AWS_DEFAULT_REGION: us-west-2
  commands:
    - aws s3 cp s3://matabit/test/.env.dev .env


# trigger:
#   status:
#   - success

# depends_on:
# - build-test

# trigger:
#   event:
#   - pull_request
#   - push
...
