---
kind: pipeline
name: build-test

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: composer
  commands:
  - composer install --prefer-dist

- name: PHPUnit Test
  image: php:7.3-rc-cli-alpine
  commands:
  - cp .env.example .env
  - php artisan key:generate
  - vendor/bin/phpunit --configuration phpunit.xml

- name: slack
  image: plugins/slack
  when:
    status: [ success, failure ]
  settings:
    webhook:
      from_secret: slack_webhook
    channel: classrooms-drone
    template: >
      {{#success build.status}}
        Build {{build.number}} succeeded. Good job.
      {{else}}
        Build {{build.number}} failed. Fix me please.
      {{/success}}

- name: deploy  
  image: plugins/ecr
  settings:
    access_key: 
       from_secret: aws_access_key_id
    secret_key: 
       from_secret: aws_secret_access_key
    repo:
       from_secret: ecr_repo
    registry:
       from_secret: ecr_registry
    region: us-west-2

# trigger:
#   event:
#   - pull_request
# ---
# kind: pipeline
# name: deploy
# steps:



# trigger:
#   status:
#   - success

# depends_on:
# - build-test

# trigger:
#   event:
#   - pull_request
#   - push
...
