---
kind: pipeline
name: Backend Test

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: composer:latest
  commands:
  - composer install --no-interaction --ignore-platform-reqs --no-plugins --no-scripts

- name: PHPUnit Test
  image: ainlavong/cp-test:latest
  commands:
  - cp .env.test .env
  - php artisan key:generate
  - php artisan migrate --seed
  - vendor/bin/phpunit --configuration phpunit.xml

services:
- name: database
  image: mariadb
  ports:
  - 3306
  environment:
    MYSQL_ROOT_PASSWORD: test
    MYSQL_DATABASE: test

- name: Slack
  image: plugins/slack
  when:
  status: [ success, failure ]
  settings:
    webhook:
      from_secret: slack_webhook
    channel: classrooms-drone
    template: >
      {{#success build.status}}
        Build {{build.number}} succeeded. Good job.
      {{else}}
        Build {{build.number}} failed. Fix me please.
      {{/success}}

trigger:
  event:
  - pull_request
---
kind: pipeline
name: Frontend Test

platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: node:carbon-alpine
  commands:
    - npm i

- name: Test
  image: node:carbon-alpine
  commands:
    - npm test

trigger:
  event:
  - pull_request
...
