---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: composer
  commands:
  - composer install --prefer-dist

- name: PHPUnit Test
  image: php:7.3-rc-cli-alpine
  commands:
  - php -v
  - cp .env.example .env
  - php artisan key:generate
  - vendor/bin/phpunit --configuration phpunit.xml

- name: Deploy to ECR test
  image: alpine:latest
  commands:
  - echo "$DB_HOST" > wow.txt
  - cat wow.txt
...
