version: '3'

services:
  webserver:
    container_name: classroom-profiles
    image: ainlavong/classroom-profiles
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8000:8080'
  composer:
    restart: 'no'
    container_name: composer
    image: composer:latest
    command: install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts --prefer-dist
    volumes:
      - .:/app/